/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MrginghamJNI */

#ifndef _Included_MrginghamJNI
#define _Included_MrginghamJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MrginghamJNI
 * Method:    detectChessboardNative
 * Signature: (JZI)[Ljava/lang/Object;
 */
JNIEXPORT jobjectArray JNICALL Java_MrginghamJNI_detectChessboardNative
  (JNIEnv *, jclass, jlong, jboolean, jint, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
